### ISSUE TITLE
Save denoised dataset as CSV

### ISSUE THREAD

**Issue by Amrican10** [fperdigon/DeepFilter#31]
I am asking if it possible to save the denoised dataset as a CSV file to be used for further classification? Thanks

**Comment by fperdigon** [comment]
Yes, it's possible, for that you need to use the python CSV lib.
Please do not use the issues on the repos to communicate with the authors.
This channel is dedicated to real issues not general questions

**Comment by fperdigon** [comment]
Closing this since it was never an issue
